// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT4gvBOQYJY_lAj-lXJToxKQTrcKA7stk',
    appId: '1:299645351864:web:03680fe5f54ac256fd414d',
    messagingSenderId: '299645351864',
    projectId: 'runningapp-ee9d9',
    authDomain: 'runningapp-ee9d9.firebaseapp.com',
    databaseURL: 'https://runningapp-ee9d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'runningapp-ee9d9.appspot.com',
    measurementId: 'G-SQLNXLDYTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQbFOY47yS8_SO_ObT1ZX-IqYhCRQJgCU',
    appId: '1:299645351864:android:0f7f205348ddb7b3fd414d',
    messagingSenderId: '299645351864',
    projectId: 'runningapp-ee9d9',
    databaseURL: 'https://runningapp-ee9d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'runningapp-ee9d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJqWkPmGXGDTjEA-mJRztU_A-7echIQ8E',
    appId: '1:299645351864:ios:0b8ebbb994afeacefd414d',
    messagingSenderId: '299645351864',
    projectId: 'runningapp-ee9d9',
    databaseURL: 'https://runningapp-ee9d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'runningapp-ee9d9.appspot.com',
    iosBundleId: 'com.example.runningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJqWkPmGXGDTjEA-mJRztU_A-7echIQ8E',
    appId: '1:299645351864:ios:0b8ebbb994afeacefd414d',
    messagingSenderId: '299645351864',
    projectId: 'runningapp-ee9d9',
    databaseURL: 'https://runningapp-ee9d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'runningapp-ee9d9.appspot.com',
    iosBundleId: 'com.example.runningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT4gvBOQYJY_lAj-lXJToxKQTrcKA7stk',
    appId: '1:299645351864:web:2ef003f75b1c05defd414d',
    messagingSenderId: '299645351864',
    projectId: 'runningapp-ee9d9',
    authDomain: 'runningapp-ee9d9.firebaseapp.com',
    databaseURL: 'https://runningapp-ee9d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'runningapp-ee9d9.appspot.com',
    measurementId: 'G-BJDVTNVQ2T',
  );
}
